language: java
sudo: false
 
cache:
	directories:
	- "$HOME/.m2"
 
before_cache:
- rm -rf $HOME/.m2/repository/com/autentia/traviscodacy
 
jdk:
	- oraclejdk8

script: "mvn cobertura:cobertura"

after_success:
- bash <(curl -s https://codecov.io/bash)